var compo = compo || {};
compo = {
	main_contents : ()=>{
		return '<div class="main_top">'
		+'		<div class="wrap">'
		+'			<div class="main_top_title">나만의 여행 플래너 여길가자!</div>'
		+'			<div class="main_top_desc">쉽고 빠르게 여행을 계획하세요.</div>'
		+'			<div class="search_area">'
		+'				<div id="city_autocomplete"></div>'
		+'				<div class="latest_search">'
		+'					추천도시 : <a href="/ko/czity/london_309" class="latest_a">런던</a> , <a'
		+'						href="/ko/city/jeju_312" class="latest_a">제주도</a> , <a'
		+'						href="/ko/city/hong-kong_245" class="latest_a">홍콩</a>'
		+'				</div>'
		+'				<a class="go_map" href="javascript:void(0)"></a>'
		+'				<div class="clear"></div>'
		+'			</div>'
		+'		</div>'
		+'	</div>'
		+'<div id="contents"></div>'
		+'<div class="wrap" style="padding-top:30px; padding-bottom:30px">'
		+'<div class="page_title">'
		+'최근 여행일정'
		+'</div>'
		+'<div class="page_desc">'
			+'다른 여행자들의 일정을 참고해 나만의 여행을 계획해보세요!'
		+'</div>'
		+'<div class="plan_list">'
		+'<a href="" target="_blank" class="box"><div class="plan_bg">'
		+'<div class="plan_bg_inner"><span>2015-04-30</span><span class="tour_day">1DAYS</span><br>Big Bus Blue - 침사추이</div></div>'
		+'<div class="plan_img_box">	'
		+'<img src="http://img.earthtory.com/img/plan_cover_img/42175_1430882489.jpg" alt="" class="plan_img"></div>'
		+'<div class="plan_bg_inner2">'
		+'<span>나홀로 여행</span>'
		+'<div class="fr pn_list_copy_icon">5</div>'
		+'<div class="fr pn_list_view_icon">1013</div>'
		+'<div class="fr pn_list_spot_icon">8</div>'
		+'<div class="clear"></div>'
		+'<div class="pn_list_city">홍콩</div>'
		+'<div class="clear"></div>'
		+'<div class="pn_list_user">여행마니아</div></div>'
		+'</a>'
		+'<a href="" target="_blank" class="box">'
		+'<div class="plan_bg">'
		+'<div class="plan_bg_inner">'
		+'<span>2015-08-10</span>'
		+'<span class="tour_day">6DAYS</span><br>대만여행!</div></div>'
		+'<div class="plan_img_box">	'
		+'<img src="http://img.earthtory.com/img/city_images/92/taipei_1425530247.jpg" alt="" class="plan_img"></div>'
		+'<div class="plan_bg_inner2"><span>친구와 함께</span><div class="fr pn_list_copy_icon">0</div>'
		+'<div class="fr pn_list_view_icon">226</div><div class="fr pn_list_spot_icon">28</div>'
		+'<div class="clear"></div>'
		+'<div class="pn_list_city">타이베이,타이중</div>'
		+'<div class="clear"></div><div class="pn_list_user">정예성</div></div></a>'
		+'<a href="" target="_blank" class="box">'
		+'<div class="plan_bg"><div class="plan_bg_inner"><span>2015-09-22</span>'
		+'<span class="tour_day">6DAYS</span><br>설레는 싱가폴여행!</div></div>'
		+'<div class="plan_img_box">	'
		+'<img src="http://img.earthtory.com/img/city_images/243/singapore_1425521353.jpg" alt="" class="plan_img"></div>'
		+'<div class="plan_bg_inner2"><span>가족 여행</span>'
		+'<div class="fr pn_list_copy_icon">0</div>'
		+'<div class="fr pn_list_view_icon">164</div>'
		+'<div class="fr pn_list_spot_icon">47</div><div class="clear"></div>'
		+'<div class="pn_list_city">싱가포르</div><div class="clear"></div>'
		+'<div class="pn_list_user">김민주,김종록</div></div></a>'
		+'<a href="" target="_blank" class="box">'
		+'<div class="plan_bg">'
		+'<div class="plan_bg_inner"><span>2015-07-30</span>'
		+'<span class="tour_day">18DAYS</span><br>동유럽급여행</div></div>'
		+'<div class="plan_img_box"> <img src="http://img.earthtory.com/img/city_images/10016/berlin_1426832124.jpg" class="plan_img"></div>'
		+'<div class="plan_bg_inner2"><span>커플 여행</span>'
		+'<div class="fr pn_list_copy_icon">0</div>'
		+'<div class="fr pn_list_view_icon">185</div>'
		+'<div class="fr pn_list_spot_icon">111</div>'
		+'<div class="clear"></div><div class="pn_list_city">프라하,베를린,크라쿠프,바르샤바,부다페스트,빈...</div>'
		+'<div class="clear"></div>'
		+'<div class="pn_list_user">조은영</div></div></a>'
		+'<a href="" target="_blank" class="box"><div class="plan_bg">'
		+'<div class="plan_bg_inner"><span>2015-05-24</span>'
		+'<span class="tour_day">4DAYS</span>'
		+'<br>홍콩 마카오 3N4D</div></div>'
		+'<div class="plan_img_box">	'
		+'<img src="http://img.earthtory.com/img/city_images/245/hong-kong_1429504145.jpg" alt="" class="plan_img"></div>'
		+'<div class="plan_bg_inner2"><span>가족 여행</span>'
		+'<div class="fr pn_list_copy_icon">25</div><div class="fr pn_list_view_icon">26</div>'
		+'<div class="fr pn_list_spot_icon">42</div><div class="clear"></div><div class="pn_list_city">홍콩,마카오</div>'
		+'<div class="clear"></div>'
		+'<div class="pn_list_user">김아름</div></div></a>'
		+'<a href="" target="_blank" class="box">'
		+'<div class="plan_bg"><div class="plan_bg_inner"><span>2015-06-13</span>'
		+'<span class="tour_day">3DAYS</span><br>2015년 6월 도쿄여행</div></div>'
		+'<div class="plan_img_box">'
		+'<img src="http://img.earthtory.com/img/city_images/295/tokyo_1426774311.jpg" alt="" class="plan_img"></div>'
		+'<div class="plan_bg_inner2"><span>커플 여행</span><div class="fr pn_list_copy_icon">1</div>'
		+'<div class="fr pn_list_view_icon">171</div><div class="fr pn_list_spot_icon">78</div>'
		+'<div class="clear"></div><div class="pn_list_city">도쿄</div>'
		+'<div class="clear"></div><div class="pn_list_user">김상운</div></div></a>'
		+'<div class="clear"></div></div>'
		+'<div class="more_btn" onclick="">'
		+'56,065개의 추천일정 모두보기'
		+'</div>'
		+'</div>' 
		+'<div class="page silver">'
		+'<div class="wrap">'
		+'<div class="page_title">'
		+'인기나라 TOP10		</div>'
		+'<div id="top_city_list" class="top_city_list">'
		+'                    </div>'
		+'                </div>'
		+'            </div>'
	},
	logon : ()=>{
		return 	'<div class="dropdown">'
		  +'    <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown">'
  		  +'    <span class="caret"></span></button>'
  		  +'    <ul class="dropdown-menu">'
  		  +'      <li><a href="#">마이페이지</a></li>'
  		  +'      <li class="divider"></li>'
  		  +'      <li id="logout_btn" ><a href="#">로그아웃</a></li>'
  		  +'    </ul>'
  		  +'  </div>'
	},
	// 이창준
	tourist_area : ()=>{
		return '<div class="area_top" id="area_top">'
		+'<div class="wrap">'
		+'	<div class="area_top_title">어디로 여행을 가시나요?</div>'
		+'		<div class="search_area">'
		+'			<input class="search_input" id="city_search" placeholder="국가명, 도시명으로 검색">'
		+'			<div id="city_autocomplete"></div>'
		+'			<div class="latest_search">	추천도시 :<a href="/ko/city/singapore_243" class="latest_a">싱가포르</a>'
		+'				,<a href="/ko/city/paris_307" class="latest_a">파리</a>'
		+'				,<a href="/ko/city/jeju_312" class="latest_a">제주도</a>'
		+'		</div>'
		+'			<a class="go_map" href="javascript:void(0)" onclick="et_full_modal("/ko/modal/world_map")">지도에서 검색 ></a>'
		+'			<div class="clear"></div>'
		+'		</div>'
		+'	</div>'
		+'</div>'
		+'<div class="area_white">'
		+'	<div class="wrap">'
		+'		<div class="area_title">'
		+'			국가리스트		</div>'
		+'		<div class="area_top_name as" id="area_top_name_as">'
		+'			아시아		</div>'
		+'		<div class="container" id="asia">'
		+'			<div class="clear"></div>'
		+'		</div>'
		+'		<div class="area_top_name eu" id="area_top_name_eu">'
		+'			유럽		</div>'
		+'		<div class="container" id="europe">'
		+'			<div class="clear"></div>'
		+'		</div>'
		+'	</div>'
		+'</div>'
	},
	common_menu : ()=>{
		return '<div class="area_bg top silver">' 
		+'<div class="wrap">'
		+'	<div class="area_nav">'
		+'		<a class="nav_btn cursor">여행지</a>'
		+'			&gt; '
		+'		<a class="nav_btn cursor">대만</a>'
		+'	</div>'
		+'	<div class="area_title"></div>'
		+'	<div class="common_menu">'
		+'		<div class="clear"></div>'
		+'	</div>'
		+'	</div>'
		+'</div>';
	},
	country_detail : ()=>{
		return '<div class="area_bg top silver country_detail">' 
		+'<div class="wrap">'
		+'<div class="inner_box">'
		+'<div class="img_box"></div>'
		+'		<div class="img_right">'
		+'			<div class="country_info_box">'
		+'				<div class="country_info">'
		+'					<img alt="" class="country_flag">'
		+'					<div class="country_title"></div>'
		+'					<div class="clear"></div>'
		+'					<div class="country_desc"></div>'
		+'					<a href="http://ko.wikipedia.org/wiki/대만" target="_blank" class="info_more">더보기</a>'
		+'				</div>'
		+'				<div class="country_inner_box">'
		+'					<div class="country_info_box_title">환율계산</div>'
		+'					<div class="exchange_box">'
		+'						<div class="exchange_left" data-id="1">'
		+'							<b>대만</b><br>'
		+'							<span>TWD</span>'
		+'						</div>'
		+'						<input type="text" class="exchange_input" data-no="1">'
		+'					</div>'
		+'					<div class="exchange_center">=</div>'
		+'					<div class="exchange_box">'
		+'						<div class="exchange_left" data-id="2">'
		+'							<b>대한민국</b><br><span>KRW</span>'
		+'						</div>'
		+'						<input type="text" class="exchange_input" data-no="2">'
		+'					</div>'
		+'					<div class="clear"></div>'
		+'				</div>'
		+'			</div>'
		+'		</div>'
		+'		<div class="clear"></div>'
		+'	</div>'
		+'</div>'
		+'</div>';
	},
	tourist_city : ()=>{
		return '<div class="wrap country_detail">'
		+'	<div class="category_list">'
		+'	</div>'
		+'</div>';
	},
	tourist_list : ()=>{
		return '<div class="wrap country_detail">'
		+'		<div class="list_top">'
		+'			<div class="list_cnt">'
		+'				총 <span>10</span>개		'
		+'			</div>'
		+'			<div class="list_sort">'
		+'				<select name="" id="" class="sort" data-height="25">'
		+'					<option value="pl_clip_cnt">인기순</option>'
		+'					<option value="pl_name">이름순</option>'
		+'				</select>'
		+'			</div>'
		+'		</div>'
		+''
		+'		<div id="paging">'
		+'			<span class="nv"></span>'
		+'			<button type="button" class="on">1</button>'
		+'			<button type="button">2</button>'
		+'			<button type="button">3</button>'
		+'			<button type="button">4</button>'
		+'			<button type="button">5</button>'
		+'			<button type="button">6</button>'
		+'			<button type="button">7</button>'
		+'			<button type="button">8</button>'
		+'			<button type="button">9</button>'
		+'			<button type="button">10</button>'
		+'			<span class="nv">'
		+'				<button type="button" class="pgn-nx2">다음</button>'
		+'				<button type="button" class="pgn-nx1">맨뒤로</button>'
		+'			</span>'
		+'		</div>'
		+'	<div class="clear"></div>'
		+'</div>';
	},
	attraction_list : ()=>{
		return '<div class="wrap country_detail">'
		+'	<div class="list_left">'
		+'		<div class="list_top">'
		+'			<div class="list_cnt">'
		+'			</div>'
		+'		</div>'
		+'		<div class="list">'
		+'		</div>'
		+'		<div id="paging">'
		+'			<span class="nv"></span>'
		+'		</div>'
		+'	</div>'
		+'</div>';
	},
	tourist_main_city : ()=>{
		return '<div class="wrap country_detail">'
		+'	<div class="list_left">'
		+'		<div class="list_top">'
		+'			<div class="list_cnt">'
		+'			</div>'
		+'			<div class="list_sort">'
		+'				<select name="" id="" class="sort" data-height="25">'
		+'					<option value="cnt">인기순</option>'
		+'				</select>'
		+'			</div>'
		+'		</div>'
		+'		<div class="list">'
		+'		</div>'
		+'		<div id="paging">'
		+'			<span class="nv"></span>'
		+'		</div>'
		+'	</div>'
		+'</div>';
	},
	city_detail : ()=>{
		return '<div class="area_bg top silver city_detail">' 
		+'<div class="wrap">'
		+'<div class="inner_box">'
		+'	<div class="img_box">'
		+'		</div>'
		+'		<div class="img_right">'
		+'			<div class="country_info_box">'
		+'				<div class="city_temp">'
		+'					<div class="temp_left"></div>'
		+'					<div class="temp_right">'
		+'						<div class="temp_title"></div>'
		+'						<div id="height" style="height:50px"></div>'
		+''
		+'<div class="w-grid-container">'
		+'</div>'
		+'						</div>'
		+'					</div>'
		+'					<div class="clear"></div>'
		+'				</div>'
		+''
		+'				<div class="country_inner_box">'
		+'					<div class="country_info_box_title">환율 계산</div>'
		+'					<div class="exchange_box e1">'
		+'						<div class="exchange_left">'
		+'							<b>대만</b><br>'
		+'							<span>TWD</span>'
		+'						</div>'
		+'						<input type="text" class="exchange_input" data-no="1">'
		+'					</div>'
		+'					<div class="exchange_center">=</div>'
		+'					<div class="exchange_box e2">'
		+'						<div class="exchange_left">'
		+'							<b>대한민국</b><br>'
		+'							<span>KRW</span>'
		+'						</div>'
		+'						<input type="text" class="exchange_input" data-no="2">'
		+'					</div>'
		+'					<div class="clear"></div>'
		+'				</div>'
		+'			</div>'
		+'		</div>'
		+'		<div class="clear"></div>'
		+'	</div>'
		+'</div>'
		+'</div>';
	},
	city_topten : ()=>{
		return '<div class="area_bg line spot_list silver">'
		+'	<div class="wrap">'
		+'		<div class="area_title_center city_po">타이베이 인기장소</div>'
		+'		<div class="pospot_content">'
		+'			<a class="pospot" href="/ko/city/taipei_92/attraction/taipei-101-observatory_1169" target="_blank">'
		+'				<div class="po_img_box">'
		+'					<img src="http://img.earthtory.com/img/place_img/92/1169_0_et.jpg" alt="" class="po_img" >'
		+'				</div>'
		+'				<div class="po_name">타이베이101관경대</div>'
		+'				<div class="po_bottom">'
		+'					<img src="/res/img/city/clip_icon.png" alt="" class="po_clip">'
		+'					<div class="po_cnt">9,947</div>'
		+'					<div class="po_tag">랜드마크</div>'
		+'					<div class="clear"></div>'
		+'				</div>'
		+'			</a>'
		+'			<a class="pospot" href="/ko/city/taipei_92/attraction/xi-men-street_1163" target="_blank">'
		+'				<div class="po_img_box">'
		+'					<img src="http://img.earthtory.com/img/place_img/92/1163_0_et.jpg" alt="" class="po_img">'
		+'				</div>'
		+'				<div class="po_name">시먼딩</div>'
		+'				<div class="po_bottom">'
		+'					<img src="/res/img/city/clip_icon.png" alt="" class="po_clip">'
		+'					<div class="po_cnt">9,525</div>'
		+'					<div class="po_tag">유명한거리/지역</div>'
		+'					<div class="clear"></div>'
		+'				</div>'
		+'			</a>'
		+'			<a class="pospot" href="/ko/city/taipei_92/shopping/shilin-night-market_1201" target="_blank">'
		+'				<div class="po_img_box">'
		+'					<img src="http://img.earthtory.com/img/place_img/92/1201_0_et.jpg" alt="" class="po_img">'
		+'				</div>'
		+'				<div class="po_name">스린야시장</div>'
		+'				<div class="po_bottom">'
		+'					<img src="/res/img/city/clip_icon.png" alt="" class="po_clip">'
		+'					<div class="po_cnt">9,502</div>'
		+'					<div class="po_tag">시장/쇼핑거리</div>'
		+'					<div class="clear"></div>'
		+'				</div>'
		+'			</a>'
		+'			<a class="pospot" style="margin-right:0px;" href="/ko/city/taipei_92/attraction/jiufen_5748" target="_blank">'
		+'				<div class="po_img_box">'
		+'					<img src="http://img.earthtory.com/img/place_img/92/5748_0_et.jpg" alt="" class="po_img">'
		+'				</div>'
		+'				<div class="po_name">지우펀</div>'
		+'				<div class="po_bottom">'
		+'					<img src="/res/img/city/clip_icon.png" alt="" class="po_clip">'
		+'					<div class="po_cnt">9,210</div>'
		+'					<div class="po_tag">유명한거리/지역</div>'
		+'					<div class="clear"></div>'
		+'				</div>'
		+'			</a>'
		+'		</div>'
		+'	</div>'
		+'</div>';
	},
	restaurant_city : ()=>{
		return '<div class="wrap country_detail">'
		+'	<div class="category_list">'
		+'		<div class="attraction_menu">'
		+'			<div class="clear"></div>'
		+'		</div>'
		+'		<div class="category_box first">'
		+'			<div class="category_btn" data-id="301012" data-on="off">현지요리</div>'
		+'			<div class="category_btn" data-id="301011" data-on="off">카페/디저트/베이커리</div>'
		+'			<div class="category_btn" data-id="301010" data-on="off">닭/오리요리</div>'
		+'			<div class="category_btn" data-id="301009" data-on="off">딤섬</div>'
		+'			<div class="clear"></div>'
		+'		</div>'
		+'		<div class="category_box ">'
		+'			<div class="category_btn" data-id="301008" data-on="off">면요리</div>'
		+'			<div class="category_btn" data-id="303001" data-on="off">북미요리</div>'
		+'			<div class="category_btn" data-id="302007" data-on="off">뷔페</div>'
		+'			<div class="category_btn" data-id="301007" data-on="off">스테이크/바비큐</div>'
		+'			<div class="clear"></div>'
		+'		</div>'
		+'		<div class="category_more" data-on="off">'
		+'			<span>카테고리 더보기</span>'
		+'		</div>'
		+'	</div>'
		+'</div>';
	},
	shopping_city : ()=>{
		return '<div class="wrap country_detail">'
		+'	<div class="category_list">'
		+'		<div class="attraction_menu">'
		+'			<div class="clear"></div>'
		+'		</div>'
		+'		<div class="category_box first">'
		+'			<div class="category_btn" data-id="301012" data-on="off">마트/식료품</div>'
		+'			<div class="category_btn" data-id="301011" data-on="off">면세점/아울렛</div>'
		+'			<div class="category_btn" data-id="301010" data-on="off">생활용품/기념품</div>'
		+'			<div class="category_btn" data-id="301009" data-on="off">쇼핑몰/백화점</div>'
		+'			<div class="clear"></div>'
		+'		</div>'
		+'		<div class="category_box ">'
		+'			<div class="category_btn" data-id="301008" data-on="off">시장/쇼핑거리</div>'
		+'			<div class="category_btn" data-id="303001" data-on="off">전문상점</div>'
		+'			<div class="category_btn" data-id="302007" data-on="off">화장품</div>'
		+'			<div class="clear"></div>'
		+'		</div>'
		+'	</div>'
		+'</div>';
	},
//	정지우
		plan_header : ()=>{
			return '<div class="plan_header" id="plan_header">'
			+'<div class="wrap">'
			+'<div class="p_header_title">'
				+'누구나 쉽게 일정을 계획할 수 있습니다.</div>'
			+'<div class="p_header_img">'
				+'<img id="p_header_img" alt="" />'
			+'</div>'
			+'<div class="p_header_btn_box">'
				
				+'<div class="clear"></div>'
			+'</div>'
			+'<img class="p_header_hide_bg" id="p_header_hide_bg"/>'
			+'</div>'
			+'</div>'},
			
		plan_content: ()=>{
			return '<div class="content">'
			+'<div class="wrap">'
			+'<div class="content_header">'
				+'<div class="content_header_title">'
				+'여행자들의 일정보기</div>'
				+'<div class="clear"></div>'
			+'</div>'
			+'<div class="content_filter">'
			+'<input type="hidden" id="cu_srl">'
			+'<input type="hidden" id="ci_srl">'
			+'<input type="hidden" id="tour_day">'
			+'<input type="hidden" id="tour_month">'
			+'<input type="hidden" id="tour_type">'
			+'<div class="filter_title f_title">'
			+'필터			</div>'
			+'<div class="filter_right f_content">'
			+'</div>'
			+'<div class="clear"></div>'
		
		+'<div class="filter_title" data-sh="area_tab">'
		+'여행지			</div>'
		+'<div class="filter_right" data-sh="area_tab">'
				+'<div class="filter_set_btn" data-hide="area_tab" data="205">국내</div>'
				+'<div class="filter_set_btn" data-hide="area_tab" data="6">일본</div>'
				+'<div class="filter_set_btn" data-hide="area_tab" data="28">홍콩</div>'
				+'<div class="filter_set_btn" data-hide="area_tab" data="19">싱가포르</div>'
				+'<div class="filter_set_btn" data-hide="area_tab" data="26">대만</div>'
				+'<div class="filter_set_btn" data-hide="area_tab" data="25">태국</div>'
				+'<div class="filter_set_btn" data-hide="area_tab" data="300">미국</div>'
				+'<div class="filter_set_btn" data-hide="area_tab" data="203">프랑스</div>'
				+'<div class="area_btn" data-on="off">'
					+'<img id="area_btn" alt="">'
				+'</div>'
				+'<div class="clear"></div>'
			+'</div>'
			+'<div class="clear"></div>'
			+'<div class="area_tab" data-sh="area_tab">'
				+'<div class="area_tab_box">'
					+'<div class="area_tab_btn on" data-on="on" data-tab="as">'
					+'아시아					</div>'
					+'<div class="area_tab_btn" data-on="off" data-tab="eu">'
					+'유럽					</div>'
					+'<div class="area_tab_btn" data-on="off" data-tab="oc">'
					+'남태평양					</div>'
					+'<div class="area_tab_btn" data-on="off" data-tab="na">'
					+'북미					</div>'
					+'<div class="area_tab_btn" data-on="off" data-tab="sa">'
					+'중남미					</div>'
		
		+'<img class="areatab_close" alt="">'
		+'<div class="areatab_line"></div>'
		+'<div class="autobox">'
						+'<input type="text" class="area_search" placeholder="여행지를 검색하세요.">'
						+'<div class="autos"></div>'
					+'</div>'
					+'<div class="clear"></div>'
				+'</div>'
				+'<div class="tab as on">'
		
		+'<div class="filter_set_btn w8" data-hide="area_tab" data="6">일본</div><div class="filter_set_btn w8" data-hide="area_tab" data="9">마카오</div>'
		+'<div class="filter_set_btn w8" data-hide="area_tab" data="10">말레이시아</div><div class="filter_set_btn w8" data-hide="area_tab" data="15">베트남</div>'
		+'<div class="filter_set_btn w8" data-hide="area_tab" data="19">싱가포르</div><div class="filter_set_btn w8" data-hide="area_tab" data="20">인도</div>'
					+'<div class="filter_set_btn w8" data-hide="area_tab" data="23">중국</div><div class="filter_set_btn w8" data-hide="area_tab" data="24">캄보디아</div>'
					+'<div class="filter_set_btn w8" data-hide="area_tab" data="25">태국</div><div class="filter_set_btn w8" data-hide="area_tab" data="26">대만</div>'
					+'<div class="filter_set_btn w8" data-hide="area_tab" data="28">홍콩</div><div class="filter_set_btn w8" data-hide="area_tab" data="202">필리핀</div>'
					+'<div class="filter_set_btn w8" data-hide="area_tab" data="205">대한민국</div><div class="filter_set_btn w8" data-hide="area_tab" data="301">인도네시아</div>'
					+'<div class="filter_set_btn w8" data-hide="area_tab" data="328">라오스</div><div class="filter_set_btn w8" data-hide="area_tab" data="330">미얀마(버마)</div>'
					+'<div class="filter_set_btn w8" data-hide="area_tab" data="338">네팔</div><div class="filter_set_btn w8" data-hide="area_tab" data="344">몰디브</div>'
					+'<div class="filter_set_btn w8" data-hide="area_tab" data="345">스리랑카</div><div class="clear"></div></div>'
					+'<div class="tab eu">'
		
						+'<div class="filter_set_btn w8" data-hide="area_tab" data="64">오스트리아</div><div class="filter_set_btn w8" data-hide="area_tab" data="66">이탈리아</div>'
						+'<div class="filter_set_btn w8" data-hide="area_tab" data="68">체코</div><div class="filter_set_btn w8" data-hide="area_tab" data="70">크로아티아</div>'
						+'<div class="filter_set_btn w8" data-hide="area_tab" data="72">터키</div><div class="filter_set_btn w8" data-hide="area_tab" data="74">폴란드</div>'
						+'<div class="filter_set_btn w8" data-hide="area_tab" data="77">헝가리</div><div class="filter_set_btn w8" data-hide="area_tab" data="203">프랑스</div>'
						+'<div class="filter_set_btn w8" data-hide="area_tab" data="204">영국</div><div class="filter_set_btn w8" data-hide="area_tab" data="208">스페인</div>'
						+'<div class="filter_set_btn w8" data-hide="area_tab" data="210">독일</div><div class="filter_set_btn w8" data-hide="area_tab" data="211">스위스</div>'
						+'<div class="filter_set_btn w8" data-hide="area_tab" data="303">네덜란드</div><div class="filter_set_btn w8" data-hide="area_tab" data="306">벨기에</div>'
						+'<div class="filter_set_btn w8" data-hide="area_tab" data="307">모나코</div><div class="filter_set_btn w8" data-hide="area_tab" data="308">포르투갈</div>'
						+'<div class="filter_set_btn w8" data-hide="area_tab" data="309">아일랜드</div><div class="filter_set_btn w8" data-hide="area_tab" data="310">아이슬란드</div>'
						+'<div class="filter_set_btn w8" data-hide="area_tab" data="311">스웨덴</div><div class="filter_set_btn w8" data-hide="area_tab" data="313">그리스</div>'
						+'<div class="filter_set_btn w8" data-hide="area_tab" data="329">덴마크</div><div class="filter_set_btn w8" data-hide="area_tab" data="331">핀란드</div>'
						+'<div class="filter_set_btn w8" data-hide="area_tab" data="332">러시아</div><div class="filter_set_btn w8" data-hide="area_tab" data="333">노르웨이</div>'
						+'<div class="filter_set_btn w8" data-hide="area_tab" data="334">슬로베니아</div><div class="filter_set_btn w8" data-hide="area_tab" data="335">보스니아 헤르체고비나</div>'
						+'<div class="filter_set_btn w8" data-hide="area_tab" data="346">루마니아</div><div class="filter_set_btn w8" data-hide="area_tab" data="347">불가리아</div>'
						+'<div class="filter_set_btn w8" data-hide="area_tab" data="348">룩셈부르크</div><div class="clear"></div></div>'
						+'<div class="tab oc">'
		
		+'<div class="filter_set_btn w8" data-hide="area_tab" data="206">오스트레일리아</div><div class="filter_set_btn w8" data-hide="area_tab" data="209">괌</div>'
		+'<div class="filter_set_btn w8" data-hide="area_tab" data="302">사이판</div><div class="filter_set_btn w8" data-hide="area_tab" data="318">뉴질랜드</div>'
		+'<div class="filter_set_btn w8" data-hide="area_tab" data="319">뉴칼레도니아</div><div class="filter_set_btn w8" data-hide="area_tab" data="350">피지</div>'
							+'<div class="filter_set_btn w8" data-hide="area_tab" data="351">프렌치폴리네시아</div><div class="clear"></div></div>'
							+'<div class="tab na">'
		
		+'<div class="filter_set_btn w8" data-hide="area_tab" data="300">미국</div><div class="filter_set_btn w8" data-hide="area_tab" data="316">캐나다</div>'
		+'<div class="clear"></div></div>'
		+'<div class="tab sa">'
		
		+'<div class="filter_set_btn w8" data-hide="area_tab" data="317">멕시코</div><div class="filter_set_btn w8" data-hide="area_tab" data="320">쿠바</div>'
		+'<div class="filter_set_btn w8" data-hide="area_tab" data="321">바하마</div><div class="filter_set_btn w8" data-hide="area_tab" data="322">자메이카</div>'
		+'<div class="filter_set_btn w8" data-hide="area_tab" data="323">페루</div><div class="filter_set_btn w8" data-hide="area_tab" data="324">아르헨티나</div>'
									+'<div class="filter_set_btn w8" data-hide="area_tab" data="325">브라질</div><div class="filter_set_btn w8" data-hide="area_tab" data="336">칠레</div>'
									+'<div class="filter_set_btn w8" data-hide="area_tab" data="337">볼리비아</div><div class="filter_set_btn w8" data-hide="area_tab" data="339">콜롬비아</div>'
									+'<div class="filter_set_btn w8" data-hide="area_tab" data="340">에콰도르</div><div class="clear"></div></div>'
								+'</div>'
		
		+'<div class="filter_title city" data-sh="city">'
		+'여행도시			</div>'
		+'<div class="filter_right city" data-sh="city">'
									+'<div class="city_box">'
									+'</div>'
									+'<div class="city_btn" data-on="off">'
										+'<img id="city_btn" src="/res/img/main/plan/area_down.jpg" alt="">'
									+'</div>'
									+'<div class="clear"></div>'
								+'</div>'
								+'<div class="clear"></div>'
		
		+'<div class="filter_title" data-sh="tour_day">'
		+'여행일			</div>'
		+'<div class="filter_right" data-sh="tour_day">'
									+'<div class="filter_set_btn" data-hide="tour_day" data="1">'
									+'1-3일				</div>'
									+'<div class="filter_set_btn" data-hide="tour_day" data="4">'
									+'4-6일				</div>'
									+'<div class="filter_set_btn" data-hide="tour_day" data="7">'
									+'7-10일				</div>'
									+'<div class="filter_set_btn" data-hide="tour_day" data="11">'
									+'11-15일				</div>'
									+'<div class="filter_set_btn" data-hide="tour_day" data="16">'
									+'15일 이상				</div>'
									+'<div class="clear"></div>'
								+'</div>'
								+'<div class="clear"></div>'
		
		+'<div class="filter_title" data-sh="tour_ss">'
		+'여행시기			</div>'
		+'<div class="filter_right" data-sh="tour_ss">'
									+'<div class="filter_set_btn" data-hide="tour_ss" data="1">'
									+'봄				</div>'
									+'<div class="filter_set_btn" data-hide="tour_ss" data="2">'
									+'여름				</div>'
									+'<div class="filter_set_btn" data-hide="tour_ss" data="3">'
									+'가을				</div>'
									+'<div class="filter_set_btn" data-hide="tour_ss" data="4">'
									+'겨울				</div>'
									+'<div class="clear"></div>'
								+'</div>'
								+'<div class="clear"></div>'
		
		+'<div class="filter_title last" data-sh="theme">'
		+'여행테마			</div>'
		+'<div class="filter_right last" data-sh="theme">'
									+'<div class="filter_set_btn" data-hide="theme" data="004">'
									+'가족여행				</div>'
									+'<div class="filter_set_btn" data-hide="theme" data="001">'
									+'나홀로여행				</div>'
									+'<div class="filter_set_btn" data-hide="theme" data="003">'
									+'커플여행				</div>'
									+'<div class="filter_set_btn" data-hide="theme" data="002">'
									+'친구와함께				</div>'
									+'<div class="filter_set_btn" data-hide="theme" data="005">'
									+'비즈니스여행				</div>'
									+'<div class="clear"></div>'
								+'</div>'
								+'<div class="clear"></div>'
							+'</div>'
		
			+'<div id="agoda_full_banner">'
				+'<script type="text/javascript" id="agoda_banner"></script>'
				+'<script type="text/javascript" src="//banner.agoda.com/js/show_ads.js"></script>'
			+'</div>'
			+'<div class="content_list">'
				+'<div class="list_h_left">'
		
					+'<div class="sort on" data-id="po">인기</div>'
					+'<div class="sort_line"></div>'
					+'<div class="sort" data-id="regdate">신규</div>'
						
				+'</div>'
				+'<div class="list_h_right">'
					+'<span class="total_cnt">41,522</span>개의 일정</div>'
					+'<div class="clear"></div>'
					+'<div class="list" id="plan_search_list" style="min-height:300px;">'
						+'<a href="/mypage/editor2?type=plan_sub&amp;gdb_srl=38278" target="_blank" class="box">'
							+'<div class="plan_bg">'
								+'<div class="plan_bg_inner"><span>2015-05-27</span><span class="tour_day">8DAYS</span><br>바르셀로나-헤로나-시체스-발렌시아</div></div><div class="plan_img_box">	'
									+'<img src="http://img.earthtory.com/img/plan_cover_img/38278_1428474001.jpg" alt="" class="plan_img"></div><div class="plan_bg_inner2"><span>가족 여행</span>'
										+'<div class="fr pn_list_copy_icon">158</div><div class="fr pn_list_view_icon">13403</div><div class="fr pn_list_spot_icon">55</div><div class="clear"></div>'
										+'<div class="pn_list_city">바르셀로나,지로나(헤로나),시체스,발렌시아</div><div class="clear"></div><div class="pn_list_user">Pro-traveler</div></div></a>'
										+'<a href="/mypage/earthtory?type=plan_sub&amp;gdb_srl=48080" target="_blank" class="box">'
		
							+'<div class="plan_bg">'
								+'<div class="plan_bg_inner"><span>2015-08-01</span><span class="tour_day">3DAYS</span><br>홍콩 - 마카오 기본 일정(3일)</div></div><div class="plan_img_box">	'
									+'<img src="http://img.earthtory.com/img/city_images/245/hong-kong_1425535341.jpg" alt="" class="plan_img"></div><div class="plan_bg_inner2"><span>커플 여행</span>'
										+'<div class="fr pn_list_copy_icon">125</div><div class="fr pn_list_view_icon">9352</div><div class="fr pn_list_spot_icon">15</div><div class="clear"></div>'
										+'<div class="pn_list_city">홍콩,마카오</div><div class="clear"></div><div class="pn_list_user">어스토리</div></div></a>'
										+'<a href="/mypage/et_564444?type=plan_sub&amp;gdb_srl=39581" target="_blank" class="box"><div class="plan_bg"><div class="plan_bg_inner"><span>2015-05-01</span>'
											+'<span class="tour_day">4DAYS</span>'
											+'<br>홍콩,마카오</div></div><div class="plan_img_box">	'
											+'<img src="http://img.earthtory.com/img/city_default/28/245.jpg" alt="" class="plan_img"></div><div class="plan_bg_inner2"><span>커플 여행</span>'
												+'<div class="fr pn_list_copy_icon">180</div><div class="fr pn_list_view_icon">7389</div><div class="fr pn_list_spot_icon">33</div><div class="clear"></div>'
												+'<div class="pn_list_city">홍콩,마카오</div><div class="clear"></div><div class="pn_list_user">Spring</div></div></a>'
												+'<a href="/mypage/editor2?type=plan_sub&amp;gdb_srl=25469" target="_blank" class="box">'
		
							+'<div class="plan_bg">'
								+'<div class="plan_bg_inner"><span>2014-10-24</span><span class="tour_day">3DAYS</span><br>2박3일 홍콩 알짜배기 일정!</div></div><div class="plan_img_box">	'
									+'<img src="http://img.earthtory.com/img/place_img/245/150_0_et.jpg" alt="" class="plan_img"></div><div class="plan_bg_inner2"><span>나홀로 여행</span>'
										+'<div class="fr pn_list_copy_icon">114</div><div class="fr pn_list_view_icon">6654</div><div class="fr pn_list_spot_icon">35</div><div class="clear"></div>'
										+'<div class="pn_list_city">홍콩</div><div class="clear"></div><div class="pn_list_user">Pro-traveler</div></div></a>'
										+'<a href="/mypage/earthtory?type=plan_sub&amp;gdb_srl=41739" target="_blank" class="box">'
		
							+'<div class="plan_bg">'
								+'<div class="plan_bg_inner"><span>2015-05-15</span><span class="tour_day">4DAYS</span><br>홍콩 마카오 3박4일 추천일정</div></div><div class="plan_img_box">	'
									+'<img src="http://img.earthtory.com/img/city_default/28/245.jpg" alt="" class="plan_img"></div><div class="plan_bg_inner2"><span>친구와 함께</span>'
										+'<div class="fr pn_list_copy_icon">90</div><div class="fr pn_list_view_icon">5612</div><div class="fr pn_list_spot_icon">57</div><div class="clear"></div'
											+'><div class="pn_list_city">홍콩,마카오</div><div class="clear"></div><div class="pn_list_user">어스토리</div></div></a>'
											+'<a href="/mypage/editor2?type=plan_sub&amp;gdb_srl=39185" target="_blank" class="box">'
		
							+'<div class="plan_bg">'
								+'<div class="plan_bg_inner"><span>2015-05-21</span><span class="tour_day">4DAYS</span><br>마드리드 3박4일 추천일정!</div></div><div class="plan_img_box">	'
									+'<img src="http://img.earthtory.com/img/plan_cover_img/39185_1429074532.jpg" alt="" class="plan_img"></div><div class="plan_bg_inner2"><span>나홀로 여행</span>'
										+'<div class="fr pn_list_copy_icon">142</div><div class="fr pn_list_view_icon">5089</div><div class="fr pn_list_spot_icon">43</div><div class="clear"></div>'
										+'<div class="pn_list_city">마드리드</div><div class="clear"></div><div class="pn_list_user">Pro-traveler</div></div></a>'
										+'<a href="/mypage/editor2?type=plan_sub&amp;gdb_srl=29895" target="_blank" class="box">'
		
							+'<div class="plan_bg">'
								+'<div class="plan_bg_inner"><span>2014-12-31</span><span class="tour_day">4DAYS</span><br>먹으러 가는 후쿠오카 겨울여행!</div></div><div class="plan_img_box">	'
									+'<img src="http://img.earthtory.com/img/place_img/286/3553_0_et.jpg" alt="" class="plan_img"></div><div class="plan_bg_inner2"><span>커플 여행</span>'
										+'<div class="fr pn_list_copy_icon">59</div><div class="fr pn_list_view_icon">5741</div><div class="fr pn_list_spot_icon">34</div><div class="clear"></div>'
										+'<div class="pn_list_city">후쿠오카</div><div class="clear"></div><div class="pn_list_user">Pro-traveler</div></div></a>'
										+'<a href="/mypage/editor2?type=plan_sub&amp;gdb_srl=41450" target="_blank" class="box">'
		
							+'<div class="plan_bg">'
								+'<div class="plan_bg_inner"><span>2015-05-02</span><span class="tour_day">4DAYS</span><br>따뜻한 봄날의 홍콩 그리고 마카오!</div></div><div class="plan_img_box">	'
									+'<img src="http://img.earthtory.com/img/plan_cover_img/41450_1430191685.jpg" alt="" class="plan_img"></div><div class="plan_bg_inner2"><span>친구와 함께</span>'
										+'<div class="fr pn_list_copy_icon">141</div><div class="fr pn_list_view_icon">4666</div><div class="fr pn_list_spot_icon">67</div><div class="clear"></div>'
										+'<div class="pn_list_city">홍콩,마카오</div><div class="clear"></div><div class="pn_list_user">Pro-traveler</div></div></a>'
										+'<a href="/mypage/et_1504160445010695040001429170301?type=plan_sub&amp;gdb_srl=39417" target="_blank" class="box">'
		
							+'<div class="plan_bg">'
								+'<div class="plan_bg_inner"><span>2015-06-01</span><span class="tour_day">3DAYS</span><br>오사카2박3일</div></div><div class="plan_img_box">	'
									+'<img src="http://img.earthtory.com/img/city_default/6/58.jpg" alt="" class="plan_img"></div><div class="plan_bg_inner2"><span>친구와 함께</span>'
										+'<div class="fr pn_list_copy_icon">101</div><div class="fr pn_list_view_icon">4411</div><div class="fr pn_list_spot_icon">42</div><div class="clear"></div>'
										+'<div class="pn_list_city">오사카</div><div class="clear"></div><div class="pn_list_user">Dallim</div></div></a>'
										+'<a href="/mypage/editor2?type=plan_sub&amp;gdb_srl=44959" target="_blank" class="box">'
		
							+'<div class="plan_bg">'
								+'<div class="plan_bg_inner"><span>2015-07-22</span><span class="tour_day">4DAYS</span><br>첫 파리여행!</div></div><div class="plan_img_box">	'
									+'<img src="http://img.earthtory.com/img/plan_cover_img/44959_1431572220.jpg" alt="" class="plan_img"></div><div class="plan_bg_inner2"><span>친구와 함께</span>'
										+'<div class="fr pn_list_copy_icon">115</div><div class="fr pn_list_view_icon">4068</div><div class="fr pn_list_spot_icon">59</div><div class="clear"></div>'
										+'<div class="pn_list_city">파리</div><div class="clear"></div><div class="pn_list_user">Pro-traveler</div></div></a>'
										+'<a href="/mypage/editor2?type=plan_sub&amp;gdb_srl=33573" target="_blank" class="box">'
		
							+'<div class="plan_bg">'
								+'<div class="plan_bg_inner"><span>2015-07-29</span><span class="tour_day">6DAYS</span><br>뉴욕 5박6일 핵심 코스</div></div><div class="plan_img_box">	'
									+'<img src="http://img.earthtory.com/img/plan_cover_img/33573_1431595163.jpg" alt="" class="plan_img"></div><div class="plan_bg_inner2"><span>친구와 함께</span>'
										+'<div class="fr pn_list_copy_icon">70</div><div class="fr pn_list_view_icon">4475</div><div class="fr pn_list_spot_icon">78</div><div class="clear"></div>'
										+'<div class="pn_list_city">뉴욕</div><div class="clear"></div><div class="pn_list_user">Pro-traveler</div></div></a>'
										+'<a href="/mypage/earthtory?type=plan_sub&amp;gdb_srl=48206" target="_blank" class="box">'
		
							+'<div class="plan_bg">'
								+'<div class="plan_bg_inner"><span>2015-08-01</span><span class="tour_day">3DAYS</span><br>오사카 실속 일정(3일)</div></div><div class="plan_img_box">	'
									+'<img src="http://img.earthtory.com/img/city_default/6/58.jpg" alt="" class="plan_img"></div><div class="plan_bg_inner2"><span>커플 여행</span>'
										+'<div class="fr pn_list_copy_icon">29</div><div class="fr pn_list_view_icon">4589</div><div class="fr pn_list_spot_icon">13</div><div class="clear"></div>'
										+'<div class="pn_list_city">오사카</div><div class="clear"></div><div class="pn_list_user">어스토리</div></div></a>'
										+'<a href="/mypage/earthtory?type=plan_sub&amp;gdb_srl=48099" target="_blank" class="box">'
		
							+'<div class="plan_bg">'
								+'<div class="plan_bg_inner"><span>2015-08-01</span><span class="tour_day">4DAYS</span><br>오사카-나라-교토 핵심 일정(4일)</div></div><div class="plan_img_box">'
									+'<img src="http://img.earthtory.com/img/city_default/6/273.jpg" alt="" class="plan_img"></div><div class="plan_bg_inner2"><span>나홀로 여행</span><div class="fr pn_list_copy_icon">56</div>'
									+'<div class="fr pn_list_view_icon">3857</div><div class="fr pn_list_spot_icon">17</div><div class="clear"></div><div class="pn_list_city">오사카,나라,교토</div>'
									+'<div class="clear"></div><div class="pn_list_user">어스토리</div></div></a><a href="/mypage/et_1503240247290931699001427176049?type=plan_sub&amp;gdb_srl=42166" target="_blank" class="box">'
		
							+'<div class="plan_bg">'
								+'<div class="plan_bg_inner"><span>2015-04-30</span><span class="tour_day">1DAYS</span><br>Big Bus Red - 홍콩섬</div></div><div class="plan_img_box">	'
									+'<img src="http://img.earthtory.com/img/plan_cover_img/42166_1430880078.jpg" alt="" class="plan_img"></div><div class="plan_bg_inner2"><span>나홀로 여행</span>'
										+'<div class="fr pn_list_copy_icon">15</div><div class="fr pn_list_view_icon">4150</div><div class="fr pn_list_spot_icon">10</div><div class="clear"></div>'
										+'<div class="pn_list_city">홍콩</div><div class="clear"></div><div class="pn_list_user">여행마니아</div></div></a>'
										+'<a href="/mypage/editor2?type=plan_sub&amp;gdb_srl=43816" target="_blank" class="box">'
		
							+'<div class="plan_bg">'
								+'<div class="plan_bg_inner"><span>2015-07-08</span><span class="tour_day">4DAYS</span><br>방콕 3박4일 추천 일정</div></div><div class="plan_img_box">	'
									+'<img src="http://img.earthtory.com/img/plan_cover_img/43816_1433751726.jpg" alt="" class="plan_img"></div><div class="plan_bg_inner2"><span>친구와 함께</span>'
										+'<div class="fr pn_list_copy_icon">42</div><div class="fr pn_list_view_icon">3751</div><div class="fr pn_list_spot_icon">53</div><div class="clear"></div>'
										+'<div class="pn_list_city">방콕</div><div class="clear"></div><div class="pn_list_user">Pro-traveler</div></div></a>'
										+'<a href="/mypage/editor2?type=plan_sub&amp;gdb_srl=43911" target="_blank" class="box">'
		
							+'<div class="plan_bg">'
								+'<div class="plan_bg_inner"><span>2015-05-23</span><span class="tour_day">3DAYS</span><br>첫 대만 자유여행!</div></div><div class="plan_img_box">	'
									+'<img src="http://img.earthtory.com/img/city_images/92/taipei_1425530262.jpg" alt="" class="plan_img"></div><div class="plan_bg_inner2"><span>가족 여행</span>'
										+'<div class="fr pn_list_copy_icon">45</div><div class="fr pn_list_view_icon">3704</div><div class="fr pn_list_spot_icon">33</div><div class="clear"></div>'
										+'<div class="pn_list_city">타이베이</div><div class="clear"></div><div class="pn_list_user">Pro-traveler</div></div></a>'
										+'<a href="/mypage/earthtory?type=plan_sub&amp;gdb_srl=41765" target="_blank" class="box">'
		
							+'<div class="plan_bg">'
								+'<div class="plan_bg_inner"><span>2015-04-24</span><span class="tour_day">3DAYS</span><br>제주도 2박3일 추천 일정</div></div><div class="plan_img_box">	'
									+'<img src="http://img.earthtory.com/img/city_default/205/312.jpg" alt="" class="plan_img"></div><div class="plan_bg_inner2"><span>커플 여행</span>'
										+'<div class="fr pn_list_copy_icon">24</div><div class="fr pn_list_view_icon">3643</div><div class="fr pn_list_spot_icon">19</div><div class="clear"></div>'
										+'<div class="pn_list_city">제주도</div><div class="clear"></div><div class="pn_list_user">어스토리</div></div></a>'
										+'<a href="/mypage/editor2?type=plan_sub&amp;gdb_srl=37565" target="_blank" class="box">'
		
							+'<div class="plan_bg">'
								+'<div class="plan_bg_inner"><span>2015-04-03</span><span class="tour_day">3DAYS</span><br>오사카 봄 여행!</div></div><div class="plan_img_box">	'
									+'<img src="http://img.earthtory.com/img/plan_cover_img/37565_1427881053.jpg" alt="" class="plan_img"></div><div class="plan_bg_inner2"><span>친구와 함께</span>'
										+'<div class="fr pn_list_copy_icon">39</div><div class="fr pn_list_view_icon">3446</div><div class="fr pn_list_spot_icon">42</div><div class="clear"></div>'
										+'<div class="pn_list_city">오사카</div><div class="clear"></div><div class="pn_list_user">Pro-traveler</div></div></a><div class="clear"></div></div>'
					+'<div id="paging"><span class="nv"></span><button type="button" class="on" onclick="get_search_plan(null,1)">1</button><button type="button" onclick="get_search_plan(null,2)">2</button>'
						+'<button type="button" onclick="get_search_plan(null,3)">3</button><button type="button" onclick="get_search_plan(null,4)">4</button><button type="button" onclick="get_search_plan(null,5)">5</button>'
						+'<button type="button" onclick="get_search_plan(null,6)">6</button><button type="button" onclick="get_search_plan(null,7)">7</button><button type="button" onclick="get_search_plan(null,8)">8</button>'
						+'<button type="button" onclick="get_search_plan(null,9)">9</button><button type="button" onclick="get_search_plan(null,10)">10</button>'
						+'<span class="nv"><button type="button" class="pgn-nx2" id="pgn-nx2" onclick="get_search_plan(null,11)">다음</button><button type="button" class="pgn-nx1" onclick="get_search_plan(null,2307)">맨뒤로</button></span></div>'
				+'</div>'
			+'</div>'
		+'</div>'
			
		},
		sche_header:()=>{
			return '<div id="sche_header">'
					+'<div class="wrap" style="width:100%;padding:0px 10px;">'
					+'<h1 class="logo fl" alt="여행의 시작! 어스토리">'
					+'<a id="jw_home"><img id="home" src="/res/img/common/gnb/logo.png" alt="여행의 시작! 어스토리" ></a>'
					+'</h1>'
					+'<div class="fl" id="gnb_plan_create_title">1.도시선택&nbsp;&nbsp;→&nbsp;&nbsp;2.상세 일정 만들기</div>'
					+'<div class="fl" id="gnb_ci_name"></div>'
					+'<div class="fr gnb_box">'
					+'<div class="fl gnb_search_box"></div>'
					+'<a href="#"><div class="fr gnb_plan_create_close_btn" id="map_close">닫기</div></a>'
					+'<div class="clear"></div>'
					+'</div>'
					+'</div>'
					+'<div class="clear"></div>'
					+'</div>'
		}, 
		sche_content:()=>{
			return '<div id="full_wrap" style="width: 100%; height: 733px;">'
			+'<div class="fl left_full_box">'
			+'<ul class="fl" id="cat_menu" data="" data-member_srl="1376703">'
				/*+'<li data="as" data-val="아시아" class=""><img id="asia" src="/res/img/workspace/new/cat_as.png" class="s"><br>아시아</li>'
				+'<li data="eu" data-val="유럽" class="on"><img src="/res/img/workspace/new/cat_eu.png" class="s"><br>유럽</li>'
				+'<li data="oc" data-val="남태평양" class=""><img src="/res/img/workspace/new/cat_oc.png" class="s"><br>남태평양</li>'
				+'<li data="na" data-val="북아메리카" class=""><img src="/res/img/workspace/new/cat_na.png" class="s"><br>북아메리카</li>'
				+'<li data="sa" data-val="중남미" class=""><img src="/res/img/workspace/new/cat_sa.png" class="s" style="padding-bottom:7px;"><br>중남미</li>'*/
			+'</ul>'
			+'<div class="fl" id="schedule_full_box" style="width:265px" data="0">'
				+'<div class="title_box">'
					+'<div id="country_list_title">'
						+'<div class="fl ct_title">유럽</div>'
						+'<div class="clear"></div>'
					+'</div>'
					+'<div id="city_list_title" style="display: none;">'
						+'<div class="back_btn fl"></div>'
						+'<div class="fl cu_title" style="width:230px;padding-left:10px;font-size:15px;">city</div>'
						+'<div class="clear"></div>'
					+'</div>'
				+'</div>'
				+'<div id="search_box" style="width:100%;height:51px;border-bottom:solid #d6d6d6 1px;"></div>'
/*				+'<div id="country_list_box" style="height: 612px;"></div>'*/
				+'<div id="city_list_box" style="height: 612px; display: none;">'
				+'</div>'
			+'</div>'
		
			+'<div class="clear"></div>'
		+'</div>'
		+'<div id="right_full_box" class="fl" style="position:absolute;left:336px;top:62px;">'
			+'<div id="clip_list" data="0">'
				+'<div class="list_title"><span></span> 클립보드<div class="list_title_option_menu" data-is_open="off">도시 변경</div></div>'
				+'<div id="detail_close_btn"></div>'
				+'<div class="clear"></div>'
				+'<div class="clipboard_change_box"></div>'
				+'<div class="list_box_overlay"></div>'
				+'<div class="list_box"></div>'
			+'</div>'
						

					+'</div>'
					+'<div class="clear"></div>'
				+'</div>'
		},
		/*-----------------------------------------------------------------------------------------------------------------*/
		
		sche_detail :()=>{
			return '<div id="select_detail_view_city" data="0">'
			+'<div class="city_title">'
				+'<div class="ci_title_name fl" style="padding-top: 13px; width: 70%"><input type="text" id="plan_title" class="form-control" placeholder="여행타이틀을 입력하세요" style="width: 220px;"></div>'
				+'<div class="pn_date_boxf fr" id="date_pick_btn" style="margin-right: 20px;" data="0">'
					+'<div class="pn_date_info fl">출발일</div>'
					+'<div class="pn_date_icon fr"><img src="'+$.img()+'/map/pn_cal_btn.png"></div>'
					+'<div class="clear"></div>'
					+'<div id="date_pick"></div>'
				+'</div>'
				+'<div class="clear"></div>'
			+'</div>'
			+'<div id="selected_cities" data="0">'
							 /*<div class="s_cities" data-lat="0" data-lng="0"><div class="city_info"><div class="del_city_btn fl"><img src="/res/img/workspace/new/del_city_btn_a.png"></div>
							 <div class="fl">서울</div>
							 	<div class="fr city_set_day_box"><div class="fl city_set_minus_btn"><img src="/res/img/workspace/new/city_item_minus_btn.png"></div>
							 	<div class="fl city_set_day_info"><span>2</span>일</div><div class="fl city_set_plus_btn"><img src="/res/img/workspace/new/city_item_plus_btn.png"></div><div class="clear"></div></div>
							 	<div class="clear"></div></div>
							 	<div class="city_route_info"><div class="city_distance_info fl">10.5Km</div><div class="city_air_search_btn fr">항공검색</div><div class="clear"></div></div></div>-->*/
		 	+'</div>'
				/*+'<div class="detail_city_bottom">'
				 	+'<div class="detail_plan_go_btn" onclick="et_modal("500px","70px","1","0","/ko/modal/create_new_plan?is_exist_city_route=true","2","1");">상세 일정 만들기</div>'
				+'</div>'*/
		+'</div>'
		+'<div class="clear"></div>'

		},
		mypage_sche : ()=>{
		    return '<div>'
		    +'  <div class="my_top_cover" center center / cover no-repeat;">'
		    +'      <div class="my_top_cover_shadow"></div>'
		    +'      <div class="cover_innter">'
		    +'          <img src="http://graph.facebook.com/812147152208679/picture?type=large" alt="" class="my_img" onerror="this.src="/res/img/common/mobile/img_profile.png";" style="background:white;">'
		    +'          <img src="http://www.earthtory.com/res/img/common/web/mgrade_8_ko.png" alt="" class="level_ico" id="level_ico">'
		    +'          <div class="my_name">Geunhyeong  In</div>'
		    +'          <div class="clear"></div>'
		    +'          <div class="my_top_title">'
		    +'              여행일정            </div>'
		    +'      </div>'
		    +'  </div>'
		    +'  <div class="my_top_menu_box">'
		    +'      <div class="my_top_menu_bg">'
		    +'      </div>'
		    +'      <div id="my_top_menu" class="my_top_menu">'
		    +'          <a class="my_menu no_line">'
		    +'              개요          </a>'
		    +'          <a class="my_menu on">'
		    +'              <!--여행일정-->여행일정           </a>'
		    +'          <a class="my_menu ">'
		    +'              <!--리뷰-->지도           </a>'
		    +'          <div class="clear"></div>'
		    +'      </div>'
		    +'  </div>'
		    +'</div>'
		    +'<div id="content">'
		    +'<div class="m_top">'
			+'<a href="/ko/plan/create" class="mtop_btn" target="_blank">'
			+'여행일정 만들기		</a>'
			+'<div class="clear"></div>'
			+'</div>'
			+'<div class="plan_inner">'
			+'<div id="paging"></div>'
			+'</div>';
		},
		/*---------------------------------------------------------------------------------------------------------------------*/
		mysche:()=>{
			return '<div id="mysche_nav" class="top_nav">'
			+'	<a href="/ko/plan">일정만들기</a>'
			+'	<span> &gt; </span>'
			+'	<a href="" class="p_user_link">여행일정</a>'
			+'	<span> &gt; </span>'
			+'	서레</div>'
			+'<div class="plan_page">'
			+'	<div class="plan_nav hide" style="">'
			+'		<div class="plan_nav_prev" data-op="prev"></div>'
			+'		<div class="plan_nav_list"><div class="plan_nav_btn  last on" data-id="1">D1 비엔티안</div></div>'
			+'		<div class="plan_nav_next" data-op="next"></div>'
			+'	</div>'
			+'	<div class="plan_cover">'
			+'		<div class="puser_box">'
			+'			<div class="fl" style="margin-right:10px;">'
			+'				<img src="/res/img/common/mobile/img_profile.png" alt="" class="puser_img">'
			+'				<div class="puser_name">박은지</div>'
			+'			</div>'
			+'			<div class="clear"></div>'
			+'		</div>'
			+'		<div id="my_cover" class="cover_img" style="background:url("http://mw2.google.com/mw-panoramio/photos/medium/77777000.jpg") no-repeat;background-size:cover;background-position:center center;"></div>'
			+'		<div class="cover_bottom">'
			+'			<div class="cover_bleft">'
			+'				<div class="plan_title">'
			+'					서레					'
			+'					<img src="/res/img/mypage/plan/sub/sb_edit.png" alt="" class="sb_edit" id="plan_info_edit">'
			+'				</div>'
			+'				<div class="plan_datetheme">'
			+'					<div class="plan_date">2019.03.08~2019.03.13 (6일)</div>'
			+'										<div class="plan_theme">'
			+'						나홀로여행					</div>'
			+'										<div class="clear"></div>'
			+'				</div>'
			+'			</div>'
			+'					</div>'
			+'	</div>'
			+'<div id="plan_mnu_box" class="plan_mnu_box" style="">'
			+'		<div class="plan_mnu" data-id="1">일정표</div>'
			+'		<div class="plan_mnu_line"></div>'
			+'		<div class="plan_mnu on" data-id="2">지도	</div>'
			+'		<div class="pdfexcel_box">'
			+'			<div class="pe_txt">'
			+'				다운로드			</div>'
			+'			<a class="down_btn pdf member_btn" href="" target="_blank"></a>'
			+'			<a class="down_btn excel member_btn" href="" target="_blank"></a>'
			+'			<div class="clear"></div>'
			+'		</div>'
			+'			<div class="plan_mnu_btn orange" id="edit_detail_plan" style="">'
			+'				수정하기			</div>'
			+'		<div class="clear"></div>'
			+'	</div>'
			+'	<div class="wrap page show" data-id="2" style="margin-top: 50px;">'
			+'		<table class="sch_table" width="100%">'
			+'			<colgroup>'
			+'				<col width="20%">'
			+'				<col width="20%">'
			+'				<col width="20%">'
			+'				<col width="20%">'
			+'				<col width="20%">'
			+'			</colgroup>'
			+'			<tbody><tr>'
			+'				<th>'
			+'					<div>'
			+'						<img src="" alt="">'
			+'						날짜						<div class="clear"></div>'
			+'					</div>'
			+'				</th>'
			+'				<th>'
			+'					<div>'
			+'						<img src="" alt="">'
			+'						나라						<div class="clear"></div>'
			+'					</div>'
			+'				</th>'
			+'				<th>'
			+'					<div>'
			+'						<img src="" alt="">'
			+'						도시						<div class="clear"></div>'
			+'					</div>'
			+'				</th>'
			+'				<th>'
			+'					<div>'
			+'						<img src="" alt="">'
			+'						일정						<div class="clear"></div>'
			+'					</div>'
			+'				</th>'
			+'				<th>'
			+'					<div>'
			+'						<img src="" alt="">'
			+'						비고						<div class="clear"></div>'
			+'					</div>'
			+'				</th>'
			+'			</tr>'
			+'		<tr class="white"><td><div class="scht_date">3월 08일 <span>(금)</span></div><div class="scht_day">DAY 1</div></td><td class="scht_vtop"><div class="scht_city">비엔티안</div><div class="scht_city_en">Vientiane</div><div class="scht_city_blank"></div></td><td></td><td class="scht_vtop"><div class="scht_spotname"><b>1.</b>CCC BAR</div><div class="scht_spotname"><b>2.</b>Beerlao Music Zone @...</div><div class="scht_spotname"><b>3.</b>Dansawanh Hotel</div><div class="scht_spotname"><b>4.</b>Moon the Night</div></td><td></td></tr><tr class="gray"><td><div class="scht_date">3월 09일 <span>(토)</span></div><div class="scht_day">DAY 2</div></td><td class="scht_vtop"><div class="scht_city">비엔티안</div><div class="scht_city_en">Vientiane</div><div class="scht_city_blank"></div></td><td></td><td class="scht_vtop"></td><td></td></tr><tr class="white"><td><div class="scht_date">3월 10일 <span>(일)</span></div><div class="scht_day">DAY 3</div></td><td class="scht_vtop"><div class="scht_city">방비엥</div><div class="scht_city_en">Vang Vieng</div><div class="scht_city_blank"></div></td><td></td><td class="scht_vtop"></td><td></td></tr><tr class="gray"><td><div class="scht_date">3월 11일 <span>(월)</span></div><div class="scht_day">DAY 4</div></td><td class="scht_vtop"><div class="scht_city">방비엥</div><div class="scht_city_en">Vang Vieng</div><div class="scht_city_blank"></div></td><td></td><td class="scht_vtop"></td><td></td></tr><tr class="white"><td><div class="scht_date">3월 12일 <span>(화)</span></div><div class="scht_day">DAY 5</div></td><td class="scht_vtop"><div class="scht_city">루앙프라방</div><div class="scht_city_en">Luang Prabang</div><div class="scht_city_blank"></div></td><td></td><td class="scht_vtop"></td><td></td></tr><tr class="gray"><td><div class="scht_date">3월 13일 <span>(수)</span></div><div class="scht_day">DAY 6</div></td><td class="scht_vtop"><div class="scht_city">루앙프라방</div><div class="scht_city_en">Luang Prabang</div><div class="scht_city_blank"></div></td><td></td><td class="scht_vtop"></td><td></td></tr></tbody></table>'
			+'			</div>'
			+'</div>'
		},
//		전서우
		reservation: ()=>{
			return '	<div id="booking" class="seo_section">'
			+'		<div class="seo_section-center">'
			+'			<div class="seo_container">'
			+'				<div id="apbtn_01" class="seo_row">'
			+'					<div id="seo_booking-form_btn" class="seo_booking-form">'
			+'						<form>'
			+'							<div class="seo_form-group">'
			+'								<div class="seo_form-checkbox">'
			+'									<label for="roundtrip">'
			+'										<input type="radio" id="roundtrip" name="flight-type">'
			+'										<span></span>왕복'
			+'									</label>'
			+'									<label for="one-way">'
			+'										<input type="radio" id="one-way" name="flight-type">'
			+'										<span></span>편도'
			+'									</label>'
			+'									<label for="multi-city">'
			+'										<input type="radio" id="multi-city" name="flight-type">'
			+'										<span></span>다구간'
			+'									</label>'
			+'								</div>'
			+'							</div>'
			+'							<div class="seo_row">'
			+'								<div class="seo_col-md-6">'
			+'									<div class="seo_form-group">'
			+'										<span id="start_01" class="seo_form-label">Flying from</span>'
													+'<input id="sinput_01" class="seo_form-control" type="text" value="인천" placeholder="출발지를 입력해주세요">'
			+'									</div>'
			+'								</div>'
			+'								<div class="seo_col-md-6">'
			+'									<div class="seo_form-group">'
			+'										<span id="dest_01" class="seo_form-label">Flyning to</span>'
													+'<input id="sinput_02" class="seo_form-control" type="text" value="타이페이" placeholder="도착지를 입력해주세요">'
			+'									</div>'
			+'								</div>'
			+'							</div>'
			+'							<div class="seo_row">'
			+'								<div class="seo_col-md-3">'
			+'									<div class="seo_form-group">'
			+'										<span id="start_02"  class="seo_form-label">Departing</span>'
			+'										<input id="sinput_03" class="seo_form-control" type="date" required="">'
			+'									</div>'
			+'								</div>'
			+'								<div class="seo_col-md-3">'
			+'									<div class="seo_form-group">'
			+'										<span id="dest_02" class="seo_form-label">Returning</span>'
			+'										<input id="sinput_04" class="seo_form-control" type="date" required="">'
			+'									</div>'
			+'								</div>'
			+'								<div class="seo_col-md-2">'
			+'									<div class="seo_form-group">'
			+'										<span id="adults_01" class="seo_form-label">Adults (18+)</span>'
			+'										<select class="seo_form-control">'
			+'											<option>1</option>'
			+'											<option>2</option>'
			+'											<option>3</option>'
			+'										</select>'
			+'										<span class="seo_select-arrow"></span>'
			+'									</div>'
			+'								</div>'
			+'								<div class="seo_col-md-2">'
			+'									<div class="seo_form-group">'
			+'										<span id="children_01" class="seo_form-label">Children (0-17)</span>'
			+'										<select class="seo_form-control">'
			+'											<option>0</option>'
			+'											<option>1</option>'
			+'											<option>2</option>'
			+'										</select>'
			+'										<span class="seo_select-arrow"></span>'
			+'									</div>'
			+'								</div>'
			+'							</div>'
			+'							<div class="seo_row">'
			+'								<div class="seo_col-md-3">'
			+'									<div class="seo_form-group">'
			+'										<span id="rank_01" class="seo_form-label">Travel class</span>'
			+'										<select class="seo_form-control">'
			+'											<option>Economy class</option>'
			+'											<option>Business class</option>'
			+'											<option>First class</option>'
			+'										</select>'
			+'										<span class="seo_select-arrow"></span>'
			+'									</div>'
			+'								</div>'
			+'								<div class="seo_col-md-3">'
			+'									<div class="seo_form-btn">'
			+'										<button id="asmbtn_01" class="seo_submit-btn">Show flights</button>'
			+'									</div>'
			+'								</div>'
			+'							</div>'
			+'						</form>'
			+'					</div>'
			+'				</div>'
			+'			</div>'
			+'		</div>'
			+'	</div>';
		},
		hreservation:()=>{
			return '	<div id="hseo_booking" class="hseo_section">'
			+'		<div class="hseo_section-center">'
			+'			<div class="hseo_container">'
			+'				<div class="hseo_row">'
			+'					<div class="hseo_col-md-7 col-md-push-5">'
			+'						<div class="hseo_booking-cta">'
			+'							<h1 id="htext_01">Make your reservation</h1><br><br>'
										+'<p id="htext_02">Lorem ipsum dolor sit amet consectetur adipisicing elit. Animi facere, soluta magnam consectetur molestias itaque'
											+'ad sint fugit architecto incidunt iste culpa perspiciatis possimus voluptates aliquid consequuntur cumque quasi.'
			+'								Perspiciatis.'
			+'							</p>'
			+'						</div>'
			+'					</div>'
			+'					<div id="hmbtn_01" class="hseo_col-md-4 col-md-pull-7">'
			+'						<div class="hseo_booking-form">'
			+'							<form>'
			+'								<div class="hseo_form-group">'
			+'									<span id="hdes_01" class="hseo_form-label">Your Destination</span>'
												+'<input class="hseo_form-control" type="text" placeholder="여행지를 입력해주세요">'
			+'								</div>'
			+'								<div class="hseo_row">'
			+'									<div class="hseo_col-sm-6">'
			+'										<div class="hseo_form-group">'
			+'											<span id="hchc_01" class="hseo_form-label">Check In</span>'
			+'											<input id="h_date_01" class="hseo_form-control" type="date" required="">'
			+'										</div>'
			+'									</div>'
			+'									<div class="hseo_col-sm-6">'
			+'										<div class="hseo_form-group">'
			+'											<span id="hchc_02" class="hseo_form-label">Check out</span>'
			+'											<input id="h_date_02" class="hseo_form-control" type="date" required="">'
			+'										</div>'
			+'									</div>'
			+'								</div>'
			+'								<div class="hseo_row">'
			+'									<div class="hseo_col-sm-4">'
			+'										<div class="hseo_form-group">'
			+'											<span id="hroom_01" class="hseo_form-label">Rooms</span>'
			+'											<select class="hseo_form-control">'
			+'												<option>1</option>'
			+'												<option>2</option>'
			+'												<option>3</option>'
			+'											</select>'
			+'											<span class="hseo_select-arrow"></span>'
			+'										</div>'
			+'									</div>'
			+'									<div class="hseo_col-sm-4">'
			+'										<div class="hseo_form-group">'
			+'											<span id="hadul_01" class="hseo_form-label">Adults</span>'
			+'											<select class="hseo_form-control">'
			+'												<option>1</option>'
			+'												<option>2</option>'
			+'												<option>3</option>'
			+'											</select>'
			+'											<span class="hseo_select-arrow"></span>'
			+'										</div>'
			+'									</div>'
			+'									<div class="hseo_col-sm-4">'
			+'										<div class="hseo_form-group">'
			+'											<span id="hchil_01" class="hseo_form-label">Children</span>'
			+'											<select class="hseo_form-control">'
			+'												<option>0</option>'
			+'												<option>1</option>'
			+'												<option>2</option>'
			+'											</select>'
			+'											<span class="hseo_select-arrow"></span>'
			+'										</div>'
			+'									</div>'
			+'								</div>'
			+'								<div class="hseo_form-btn">'
			+'									<button id="hcheck_01" class="hseo_submit-btn">Check availability</button>'
			+'								</div>'
			+'							</form>'
			+'						</div>'
			+'					</div>'
			+'				</div>'
			+'			</div>'
			+'		</div>'
			+'	</div>';
		},
		hresult:()=>{ 
			return '<div id="hotel_clean" class="page white">'
		        +'    <div class="wrap">'
		        +'        <div class="page_title">'
		        +'            검색하신 호텔입니다.!        </div>'
		        +'        <div class="clear"></div>'
		        +'        <div class="intro_list">'
		        +'        </div>'
		        +'        <div class="clear"></div>'
		        +'    </div>'
		        +'</div>';
		    },
		aresult:()=>{
			return '<div class="aseo_section-center" style="height:100px;">'
			+'      <div class="aseo_container">'
			+'        <div class="aseo_row">'
			+'          <div class="aseo_booking-form">'
			+'            <form>'
			+'              <div class="aseo_row no-margin">'
			+'                <div class="aseo_col-md-3">'
			+'                  <div class="aseo_form-group">'
			+'                    <span id="fname_02" class="aseo_form-control"></span>'
			+'                  </div>'
			+'                </div>'
			+'                <div class="aseo_col-md-6">'
			+'                  <div class="aseo_row no-margin">'
			+'                    <div class="aseo_col-md-5">'
			+'                      <div class="aseo_form-group">'
			+'                        <span id="sn_02" class="aseo_form-control"></span>'
			+'                      </div>'
			+'                    </div>'
			+'                    <div class="aseo_col-md-5">'
			+'                      <div class="aseo_form-group">'
			+'                        <span id="dn_02" class="aseo_form-control"></span>'
			+'                      </div>'
			+'                    </div>'
			+'                    <div id="col_mi2" class="aseo_col-md-2">'
			+'                      <div id="ap_02" class="aseo_form-group">'
			+'                        <span class="aseo_form-label"></span>'
			+'                        </select>'
			+'                        <span class="aseo_select-arrow"></span>'
			+'                      </div>'
			+'                    </div>'
			+'                  </div>'
			+'                </div>'
			+'                <div class="aseo_col-md-3">'
			+'                  <div class="aseo_form-btn">'
			+'                    <button id="airpay_01" class="aseo_submit-btn">예약 및 결제하기</button>'
			+'                  </div>'
			+'                </div>'
			+'              </div>'
			+'            </form>'
			+'          </div>'
			+'        </div>'
			+'      </div>'
			+'    </div><p><br>';
		},
		wells:()=>{
			return	'<div class="container">'
			+'  <table class="table">'
			+'    <thead>'
			+'    </thead>'
			+'    <tbody>'
			+'      <tr class="active">'
			+'        <td id="pnbd_01">오는편 : <br></td>'
			+'        <td id="pnbd_02">가는편 : <br></td>;'
			+'      </tr>'
			+'    </tbody>'
			+'  </table>'
			+'</div>' 
			/*'<div class="container">'
			+'  <div class="panel panel-default">'
			+'    <div id="pnbd_01" class="panel-body">가는편</div>'
			+'    <div id="pnbd_02" class="panel-body">오는편</div>'
			+'  </div>'
			+'</div>'*/;

		}
}